# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/loadData.ipynb.

# %% ../nbs/loadData.ipynb 1
from __future__ import annotations
from fastcore.docments import *
from fastcore.test import *
from fastcore.utils import *

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

from os.path import dirname, join
from tsfresh.feature_extraction import MinimalFCParameters
from tsfresh.utilities.dataframe_functions import roll_time_series
from tsfresh import extract_features

import inspect
import ipdb

# %% auto 0
__all__ = []
