# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lsf',
                'doc_host': 'https://kaiguender.github.io',
                'git_url': 'https://github.com/kaiguender/lsf',
                'lib_path': 'lsf'},
  'syms': { 'lsf.core': { 'lsf.core.BaseWeightsBasedPredictor': ('baseweightspredictor.html#baseweightsbasedpredictor', 'lsf/core.py'),
                          'lsf.core.BaseWeightsBasedPredictor.__init__': ( 'baseweightspredictor.html#baseweightsbasedpredictor.__init__',
                                                                           'lsf/core.py'),
                          'lsf.core.BaseWeightsBasedPredictor.fit': ( 'baseweightspredictor.html#baseweightsbasedpredictor.fit',
                                                                      'lsf/core.py'),
                          'lsf.core.BaseWeightsBasedPredictor.getWeightsData': ( 'baseweightspredictor.html#baseweightsbasedpredictor.getweightsdata',
                                                                                 'lsf/core.py'),
                          'lsf.core.BaseWeightsBasedPredictor.predict': ( 'baseweightspredictor.html#baseweightsbasedpredictor.predict',
                                                                          'lsf/core.py')}}}