# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lsf',
                'doc_host': 'https://kaiguender.github.io',
                'git_url': 'https://github.com/kaiguender/lsf',
                'lib_path': 'lsf'},
  'syms': {'lsf.core': {'lsf.core.foo': ('core.html#foo', 'lsf/core.py')}}}